Destination endpoints
mugberto/vacations-booking-back-end pull request #53
Opened 2021-11-12 08:09 UTC by mugberto

I created endpoints for the destination model:
- Get all destinations
- Show a detailed destination
- Create a new destination
- Delete a destination

2021-11-12 08:36 UTC, danmainah commented
Hi @mugberto 

Your linters check is not successful please check on it.

2021-11-15 08:56 UTC, ShinobiWarior requested changes
Hi @mugberto 👋🏼

STATUS: Changes required 🛑 🛑 🛑 

Great job so far, but there are still some changes to make.
Please check the comments before merging.

Cheers 🥂 and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-11-15 08:59 UTC, ShinobiWarior requested changes
Hi @mugberto 👋🏼

STATUS: Changes required 🛑 🛑 🛑 

Great job so far, but there are still some changes to make.
Please check the comments before merging.

Cheers 🥂 and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-11-15 08:59 UTC, ShinobiWarior commented on Gemfile
[Required]
Please, don't change the version of the ruby to 2.7.0 because we made an agreement earlier that we will use the 2.7.3 version.

2021-11-15 08:59 UTC, ShinobiWarior commented on config/database.yml
[Optional]
When you make changes to config/database.yml you can commit this file from your commits. That way others will not need to change it each time they pull updates.

2021-11-15 16:00 UTC, ShinobiWarior approved these changes
Hi @mugberto 👋🏼

STATUS APPROVED ✔

Your project is complete! You can merge your branch now! 

Cheers 🥂 and Happy coding!👏👏👏

2021-11-15 16:04 UTC, merged